# Generated by Django 4.2.6 on 2024-05-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
