# Generated by Django 4.2.6 on 2024-05-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_brand_slug_color_slug_currency_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile_pics/profile_photo_man.jpg', help_text='Get a representative profile image.', upload_to='profile_pics'),
        ),
    ]
