# Generated by Django 4.2.6 on 2023-10-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_product_color_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Logitech', 'Logitech'), ('Steelseries', 'Steelseries'), ('Razer', 'Razer')], default=('Logitech', 'Logitech'), max_length=50),
            preserve_default=False,
        ),
    ]
