# Generated by Django 4.2.6 on 2023-10-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_product_stocks_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
    ]
