# Generated by Django 4.2.6 on 2023-10-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Logitech', 'Logitech'), ('Steelseries', 'Steelseries'), ('Razer', 'Razer'), ('LG', 'LG'), ('DELL', 'DELL')], max_length=50),
        ),
    ]
