# Generated by Django 4.2.6 on 2023-10-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0027_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='optional_adress',
            new_name='optional_address',
        ),
    ]
