# Generated by Django 4.2.6 on 2024-05-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0037_alter_review_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
