# Generated by Django 4.2.6 on 2024-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0038_rename_image_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/profile_pics/default.jpeg', help_text='Get a representative profile image.', upload_to='media/profile_pics'),
        ),
    ]
