# Generated by Django 4.2.6 on 2024-05-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0039_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/profile_pics/default.jpeg', help_text='Get a representative profile image.', upload_to='shop/media/profile_pics'),
        ),
    ]
