# Generated by Django 4.2.6 on 2024-05-03 10:38

from django.db import migrations, models
import shopapp.libraries.validations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0040_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/profile_pics/default.jpeg', help_text='Get a representative profile image.', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, error_messages={'unique': 'First name is invalid. Try again.'}, max_length=50, validators=[shopapp.libraries.validations.FirstNameValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, error_messages={'unique': 'Last name is invalid. Try again.'}, max_length=50, validators=[shopapp.libraries.validations.LastNameValidator()]),
        ),
    ]
