# Generated by Django 4.2.6 on 2024-05-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0041_alter_profile_image_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
