# Generated by Django 4.2.6 on 2024-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0042_rename_product_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/profile_pics/899048ab0cc455154006fdb9676964b3_KlMbt9h.jpg', help_text='Get a representative profile image.', upload_to='profile_pics'),
        ),
    ]
